update

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: aws-actions/configure-aws-credentials@v2
+      - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::331146039200:role/github-action-deploy-policy
           aws-region: us-east-1
@@ -36,6 +36,7 @@ jobs:
             --output text \
             --region us-east-1)
 
+          echo "Command ID: $CMD_ID"
           echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
 
       - name: Show Results
@@ -46,8 +47,8 @@ jobs:
             --command-id "${{ steps.health.outputs.cmd_id }}" \
             --details \
             --region us-east-1 \
-            --query 'CommandInvocations[*].{Instance:InstanceId,Status:Status,IP:CommandPlugins[0].Output}' \
-            --output text
+            --query 'CommandInvocations[*].{Instance:InstanceId,Status:Status,Output:CommandPlugins[0].Output}' \
+            --output table
 
           FAILED=$(aws ssm list-command-invocations \
             --command-id "${{ steps.health.outputs.cmd_id }}" \
@@ -56,6 +57,11 @@ jobs:
             --query "length(CommandInvocations[?Status=='Failed'])" \
             --output text)
 
-          [ "$FAILED" -gt 0 ] && \
-          echo "::error::Health check failed on $FAILED instances" && \
-          echo "All instances Healthy✅"
+          echo "FAILED = $FAILED"
+
+          if [ "${FAILED:-0}" -gt 0 ]; then
+            echo "::error::$FAILED instance(s) failed the health check."
+            exit 1
+          fi
+
+          echo "✅ All instances are Healthy."
